global:
  name: consul
  image: "consul:1.15.4"
  enabled: true
  datacenter: ${datacenter}
  federation:
    enabled: ${federation}
    createFederationSecret: ${federation}
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: ${manageSystemACLs}
    createReplicationToken:  ${manageSystemACLs}
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
server:
  replicas: ${replicas}
  bootstrapExpect: ${replicas}
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  acls:
    manageSystemACLs:  ${manageSystemACLs}
connectInject:
  enabled: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: false
syncCatalog:
  enabled: false
controller:
  enabled: true
ui:
  service:
    type: 'LoadBalancer'
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: "http://prometheus-server.${prometheus_ns}.svc.cluster.local"
meshGateway:
  enabled: ${meshgateway}
  replicas: 1
metrics:
  enabled: true
  enableAgentMetrics: ${prometheus_agent_metrics}
  agentMetricsRetentionTime: 1m
  enableGatewayMetrics: true
ingressGateways:
  enabled: ${ingressgateways}
  defaults:
    replicas: 2
    service:
      type: ${ingressgateways_svc}
      annotations: |
        'prometheus.io/scrape': "true"
        'prometheus.io/port': "20200"
        'prometheus.io/path': "/metrics"
