datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server.${prometheus_ns}.svc.cluster.local
        isDefault: true
        version: 1
        editable: true
dashboards:
  default:
    consul-dashboard:
      uid: ${consul_dashboard_uid}
service:
  type: ${grafana_svc_type}

grafana.ini:
  paths:
    provisioning: /etc/grafana/provisioning

extraConfigmapMounts:
  - name: consul-dashboard
    configMap: consul-dashboard
    mountPath: /etc/grafana/dashboards/consul
    subPath: ""


dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/dashboards/consul
initChownData:
  runAsUser: 0
  fsGroup: 0
