datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server.${prometheus_ns}.svc.cluster.local
        isDefault: true
        version: 1
        editable: true
service:
  type: ${grafana_svc_type}

grafana.ini:
  paths:
    provisioning: /etc/grafana/provisioning

dashboardsConfigMaps:
  consul-dashboard: "consul-dashboard"

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'consul-dashboard'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/consul-dashboard

extraInitContainers:
  - name: decode-dashboard
    image: busybox
    command:
      - /bin/sh
      - -c
      - >
        cat /etc/grafana/consul-dashboard-base64/consul-dashboard.json.base64 | base64 -d > /var/lib/grafana/dashboards/consul-dashboard.json
    volumeMounts:
      - name: consul-dashboard-base64
        mountPath: /etc/grafana/consul-dashboard-base64
      - name: dashboards
        mountPath: /var/lib/grafana/dashboards
extraVolumes:
  - name: dashboards
    emptyDir: {}
  - name: consul-dashboard-base64
    configMap:
      name: consul-dashboard

extraVolumeMounts:
  - name: dashboards
    mountPath: /var/lib/grafana/dashboards
