datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server.${prometheus_ns}.svc.cluster.local
        isDefault: true
        version: 1
        editable: true
dashboards:
  default:
    custom-dashboard:
      file: dashboards/consul-metrics.json
      uid: ${consul_dashboard_uid}
service:
  type: ${grafana_svc_type}
