server:
  service:
    type: ${prometheus_svc_type}
  additionalScrapeConfigs:
    - job_name: 'consul-server'
      scrape_interval: 15s
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - ${consul_namespace}
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app]
          action: keep
          regex: consul
        - source_labels: [__meta_kubernetes_service_label_component]
          action: keep
          regex: server
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: metrics
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
